[package]
name = "racoon"
authors = ["roife <roifewu@gmail.com>"]
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
enum-as-inner = "0.3.3"
slotmap = "1.0"